import { normalizeBroadcastText } from "./text";

export interface CanonicalGenre {
  label: string;
  aliases: readonly string[];
}

/** Tags that are locations, brands, formats, or noise — not music genres. */
const EXCLUDED_TAG_KEYS = new Set(
  [
    "radio",
    "fm",
    "am",
    "online",
    "online only",
    "online radio",
    "internet",
    "internet radio",
    "radio online",
    "mp3",
    "aac",
    "livestream",
    "live",
    "24 7",
    "https",
    "mix",
    "top",
    "combo",
    "misc",
    "miscellaneous",
    "various",
    "features",
    "exclusive",
    "free",
    "no ads",
    "public",
    "local",
    "commercial",
    "non commercial",
    "mainstream",
    "full service",
    "concesion social",
    "concesion publica",
    "mexico",
    "mex",
    "mx",
    "cdmx",
    "mexico city",
    "ciudad de mexico",
    "ciudad de mexico",
    "jalisco",
    "sinaloa",
    "veracruz",
    "monterrey",
    "guadalajara",
    "gdl",
    "mty",
    "puebla",
    "tamaulipas",
    "durango",
    "coahuila",
    "sonora",
    "chihuahua",
    "zacatecas",
    "michoacan",
    "guanajuato",
    "aguascalientes",
    "baja california",
    "nuevo leon",
    "san luis potosi",
    "estado de mexico",
    "valle de mexico",
    "sureste",
    "veracruz city",
    "boca del rio",
    "california",
    "texas",
    "usa",
    "waynesboro",
    "norteamérica",
    "latinoamérica",
    "américa",
    "méxico",
    "estación",
    "estacion",
    "la estación exacta",
    "la estación naranja",
    "iheart radio",
    "iheart",
    "npr",
    "mvs radio",
    "mvs",
    "exa fm",
    "exa",
    "ponte exa",
    "w radio",
    "radiorama",
    "radiópolis",
    "grupo acir",
    "acir",
    "acir online",
    "grupo radio cañón",
    "grupo radio centro",
    "grupo audiorama comunicaciones",
    "grupo formula",
    "radio formula",
    "cadena rasa",
    "multimedios radio",
    "mediaset",
    "star group",
    "radio france",
    "la ke buena",
    "la mejor",
    "la mejor fm",
    "la mejor aquí nomás",
    "aquí nomás",
    "arroba fm",
    "arroba fm te conecta",
    "fm te conecta",
    "te conecta",
    "los40",
    "100 1 fm",
    "moi merino",
    "ntr medios de comunicación",
    "en todas partes",
    "programas en vivo",
    "musica en español e inglés",
    "pop en español e inglés",
    "clásicos en español e inglés",
    "noticias nacionales e internacionales",
    "noticias y comentarios",
    "noticias cortas",
    "noticias opinion",
    "noticias y música",
    "música y noticias",
    "local programming",
    "local information",
    "local music",
    "local talk",
    "local radio",
    "regional radio",
    "traffic radio broadcast",
    "traffic",
    "weather",
    "tv",
    "pri",
    "abc",
    "ard",
    "radcap",
    "radio caprice",
    "dj",
    "dj remix",
    "dj sets",
    "dj mixes",
  ].map(normalizeGenreKey),
);

export const CANONICAL_GENRES: readonly CanonicalGenre[] = [
  {
    label: "Pop",
    aliases: [
      "pop",
      "pop music",
      "música pop",
      "musica pop",
      "pop en español",
      "pop en inglés",
      "pop latino",
      "latin pop",
      "pop dance",
      "pop clásico",
      "balada pop",
      "italian pop",
      "greek pop",
      "indie pop",
      "dance pop",
      "поп-музыка",
      "popular",
      "populară",
      "top 40",
      "top40",
      "top 40 hits",
      "top hits",
      "top charts",
      "top 100",
      "hits",
      "charts",
      "contemporary hits",
      "contemporary hits radio",
      "spanish contemporary hits",
      "amor",
    ],
  },
  {
    label: "Rock",
    aliases: [
      "rock",
      "classic rock",
      "hard rock",
      "soft rock",
      "alternative rock",
      "indie rock",
      "punk rock",
      "blues rock",
      "progressive rock",
      "grunge",
      "psychedelic",
      "rock en español",
      "rock en inglés",
      "pop rock",
    ],
  },
  {
    label: "Alternative",
    aliases: ["alternative", "alternative / indie", "indie", "adult album alternative"],
  },
  {
    label: "Classical",
    aliases: ["classical", "classical music", "klassik", "opera", "piano"],
  },
  {
    label: "Jazz",
    aliases: ["jazz", "smooth jazz", "swing", "big band"],
  },
  {
    label: "Electronic",
    aliases: [
      "electronic",
      "electronica",
      "electro",
      "edm",
      "electronic dance music",
      "dance",
      "dance music",
      "house",
      "deep house",
      "tech house",
      "electro house",
      "techno",
      "trance",
      "drum and bass",
      "dnb",
      "dubstep",
      "hardstyle",
      "minimal",
      "progressive house",
      "club",
      "club dance",
      "eurodance",
      "disco",
      "italo disco",
      "progressive",
      "experimental",
      "underground",
      "industrial",
      "groove",
      "dub",
    ],
  },
  {
    label: "Hip hop",
    aliases: [
      "hip hop",
      "hip-hop",
      "hiphop",
      "rap",
      "trap",
      "urban",
      "urban contemporary",
      "urbano",
      "rnb",
      "r&b",
      "afrobeats",
    ],
  },
  {
    label: "Country",
    aliases: ["country", "country music", "classic country", "americana"],
  },
  {
    label: "Folk",
    aliases: [
      "folk",
      "folk music",
      "world",
      "world music",
      "traditional",
      "singer-songwriter",
      "acoustic",
      "celtic",
      "greek folk",
      "african music",
      "brazilian music",
      "musica italiana",
      "italian",
      "volksmusik",
    ],
  },
  {
    label: "Latin",
    aliases: [
      "latin",
      "latino",
      "latin music",
      "musica latina",
      "música en español",
      "español",
      "salsa",
      "cumbia",
      "reggaeton",
      "merengue",
      "bachata",
      "vallenato",
      "tropical",
      "música tropical",
      "tropical music",
      "música variada",
      "juvenil",
      "baladas en español",
      "balada en español",
      "balada romántica",
      "balada",
      "baladas",
      "romántica",
      "romanticas",
      "románticas",
      "música romántica",
      "musica romantica",
      "romantic",
      "romantic music",
      "love songs",
      "love",
      "crossover",
    ],
  },
  {
    label: "Regional Mexican",
    aliases: [
      "regional mexican",
      "regional mexicana",
      "música regional mexicana",
      "musica regional mexicana",
      "música popular mexicana",
      "música mexicana",
      "musica mexicana",
      "mexican music",
      "regional music",
      "música regional",
      "musica regional",
      "traditional mexican music",
      "música tradicional mexicana",
      "musica tradicional mexicana",
      "grupera",
      "grupero",
      "banda",
      "banda norteña",
      "banda tradicional",
      "norteño",
      "norteña",
      "ranchera",
      "rancheras",
      "mariachi",
      "sierreño",
      "regional",
    ],
  },
  {
    label: "Metal",
    aliases: ["metal", "heavy metal", "hardcore", "gothic"],
  },
  {
    label: "Blues",
    aliases: ["blues"],
  },
  {
    label: "Soul",
    aliases: ["soul", "funk", "funky", "motown"],
  },
  {
    label: "Reggae",
    aliases: ["reggae", "dancehall", "ska"],
  },
  {
    label: "Gospel",
    aliases: [
      "gospel",
      "christian",
      "christian music",
      "christian contemporary",
      "religious",
      "religion",
      "cristiana",
      "catholic",
      "bible",
      "islamic",
      "orthodox christian",
    ],
  },
  {
    label: "Talk",
    aliases: [
      "talk",
      "talk radio",
      "talk & speech",
      "talk show",
      "hablada",
      "radio hablada",
      "news talk",
      "news talk music",
      "entrevistas",
      "current affairs",
    ],
  },
  {
    label: "News",
    aliases: [
      "news",
      "noticias",
      "local news",
      "information",
      "información",
      "informativa",
      "world news",
      "politics",
      "economics",
    ],
  },
  {
    label: "Sports",
    aliases: ["sports", "sport", "deportes", "deporte", "sports talk", "live sports", "sports news"],
  },
  {
    label: "Oldies",
    aliases: [
      "oldies",
      "retro",
      "retro hits",
      "retro music",
      "classic hits",
      "classics",
      "clásicos",
      "golden oldies",
      "goldies",
      "nostalgia",
      "flashback",
      "decades",
      "the best of 80's",
      "60s",
      "60's",
      "60er",
      "1960s",
      "50s",
      "70s",
      "70's",
      "70er",
      "1970s",
      "80s",
      "80's",
      "80er",
      "1980s",
      "1980's",
      "90s",
      "90's",
      "90er",
      "1990s",
      "00s",
      "2000s",
      "2000er",
      "2010s",
      "2020s",
    ],
  },
  {
    label: "Easy listening",
    aliases: [
      "easy listening",
      "adult contemporary",
      "hot adult contemporary",
      "soft adult contemporary",
      "adult hits",
      "lounge",
      "lounge music",
      "chillout",
      "chillout+lounge",
      "chill",
      "relax",
      "relaxing",
      "relaxation",
      "ambient",
      "ambient and relaxation music",
      "downtempo",
      "lofi",
      "smooth",
      "meditation",
    ],
  },
  {
    label: "Entertainment",
    aliases: [
      "entertainment",
      "entretenimiento",
      "variety",
      "variety hits",
      "eclectic",
      "eclética",
      "freeform",
      "mixed",
      "comedy",
      "anime",
      "soundtrack",
      "soundtracks",
      "movie",
      "movies",
    ],
  },
  {
    label: "Culture",
    aliases: [
      "culture",
      "cultura",
      "cultural",
      "lifestyle",
      "social",
      "multicultural",
      "international",
    ],
  },
  {
    label: "Education",
    aliases: [
      "education",
      "educational",
      "university",
      "university radio",
      "college",
      "college radio",
      "student radio",
      "universitaria",
      "radio universitaria",
      "radio universidad",
      "youth",
    ],
  },
  {
    label: "Community",
    aliases: [
      "community",
      "community radio",
      "radio comunitaria",
      "public radio",
      "radio pública",
      "pública",
      "public service",
      "independent",
      "non-stop music",
    ],
  },
  {
    label: "Christmas",
    aliases: ["christmas", "christmas music"],
  },
  {
    label: "Bollywood",
    aliases: ["bollywood"],
  },
  {
    label: "K-pop",
    aliases: ["kpop", "k-pop", "jpop", "j-pop"],
  },
  {
    label: "Punk",
    aliases: ["punk"],
  },
  {
    label: "New age",
    aliases: ["new age", "new wave"],
  },
  {
    label: "Greek",
    aliases: ["greek", "greek music", "laika", "entehno"],
  },
  {
    label: "Schlager",
    aliases: ["schlager", "party", "petrecere", "manele"],
  },
  {
    label: "Sertanejo",
    aliases: ["sertanejo", "mpb"],
  },
  {
    label: "Kids",
    aliases: ["kids", "children"],
  },
  {
    label: "Old time radio",
    aliases: ["old time radio", "otr"],
  },
  {
    label: "Classic",
    aliases: ["classic", "classic country"],
  },
] as const;

export function normalizeGenreKey(value: string) {
  return normalizeBroadcastText(value)
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .replace(/['’`]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const ALIAS_TO_LABEL = new Map<string, string>();
const LABEL_TO_ALIASES = new Map<string, string[]>();

for (const genre of CANONICAL_GENRES) {
  const apiTags = new Set<string>();
  for (const alias of genre.aliases) {
    const key = normalizeGenreKey(alias);
    if (key) ALIAS_TO_LABEL.set(key, genre.label);
    apiTags.add(alias);
  }
  LABEL_TO_ALIASES.set(genre.label, [...apiTags]);
}

export function canonicalizeGenre(raw: string): string | null {
  const key = normalizeGenreKey(raw);
  if (!key || EXCLUDED_TAG_KEYS.has(key)) return null;
  return ALIAS_TO_LABEL.get(key) ?? null;
}

export function isExcludedGenreTag(raw: string) {
  return EXCLUDED_TAG_KEYS.has(normalizeGenreKey(raw));
}

export function normalizeGenreFacets(
  facets: Array<{ name: string; stationcount?: number }>,
) {
  const counts = new Map<string, number>();

  for (const facet of facets) {
    const canonical = canonicalizeGenre(facet.name);
    if (!canonical) continue;
    counts.set(
      canonical,
      (counts.get(canonical) ?? 0) + (facet.stationcount ?? 0),
    );
  }

  return [...counts.keys()].sort((left, right) =>
    left.localeCompare(right, undefined, { sensitivity: "base" }),
  );
}

export function genreSearchTags(canonicalLabel: string) {
  return LABEL_TO_ALIASES.get(canonicalLabel) ?? [canonicalLabel];
}

export function canonicalGenreLabels() {
  return CANONICAL_GENRES.map((genre) => genre.label);
}
